In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

In [3]:
import sys
sys.version

'3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]'

# creating array

In [4]:
m_list = [0,1,2,3,4,5]
m_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(m_list)

list

In [6]:
arr = np.array(m_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [9]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
np.arange(3.0)

array([0., 1., 2.])

In [12]:
np.arange(1,5)

array([1, 2, 3, 4])

In [13]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int32)

In [14]:
np.arange(-20,-10)


array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [17]:
ar = np.arange(-30,20)  # this value -30 print and 20 print without sign
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [19]:
np.arange(10,11)

array([10])

In [29]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [30]:
np.arange(0,10,3)

array([0, 3, 6, 9])

# zeros()

In [31]:
np.zeros(3)   # parameter  tunnig 

array([0., 0., 0.])

In [33]:
np.zeros(5, dtype=int) # hyperparameter tunning

array([0, 0, 0, 0, 0])

In [34]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [37]:
zeros = np.zeros([2,2])
print(zeros)
type(zeros)

[[0. 0.]
 [0. 0.]]


numpy.ndarray

In [38]:
np.zeros([2,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.zeros([10,30])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [40]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))    # bydefaul 1arge -- will give row & 2nd arg - columns

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [41]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


# ones()

In [45]:
np.ones(3)

array([1., 1., 1.])

In [47]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [49]:
n

(6, 7)

In [52]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [53]:
np.ones((5,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [54]:
np.ones((8,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# range()

In [55]:
range(5)

range(0, 5)

In [56]:
r = range(5)
print(r)

range(0, 5)


In [59]:
for i in r:
    print(i)
    


0
1
2
3
4


In [60]:
list(range(5))

[0, 1, 2, 3, 4]

In [61]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [67]:
list(range(1,30,6))

[1, 7, 13, 19, 25]

In [69]:
y = list(range(1,10))
y

[1, 2, 3, 4, 5, 6, 7, 8, 9]

# rand , randint  

In [70]:
# rand function is used np.ramdom.rand(5)

In [72]:
rand(5)

NameError: name 'rand' is not defined

In [77]:
np.random.rand(2,4)

array([[0.63307922, 0.28865518, 0.30265875, 0.69312799],
       [0.93594906, 0.62523679, 0.41684858, 0.61484778]])

In [92]:
np.random.randint(1,50)

49

In [99]:
np.random.randint(10,20,4)

array([10, 11, 19, 14])

In [102]:
np.random.randint(-30,20,10)

array([  7,  -7,  -8, -19, -18,  15, -19, -26,   1, -25])

In [105]:
np.random.randint(20,30,10) 

array([27, 23, 23, 22, 28, 22, 24, 27, 20, 21])

In [111]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

8

In [115]:
np.random.randint(10,50,(10,10))

array([[19, 36, 24, 28, 19, 44, 25, 10, 12, 43],
       [17, 32, 35, 46, 45, 43, 16, 30, 24, 32],
       [18, 18, 31, 49, 45, 20, 26, 47, 12, 42],
       [46, 21, 15, 26, 41, 36, 12, 44, 21, 48],
       [23, 40, 12, 38, 23, 48, 30, 11, 44, 46],
       [23, 46, 31, 30, 34, 47, 49, 41, 15, 41],
       [31, 24, 27, 45, 13, 43, 11, 14, 15, 20],
       [27, 37, 20, 27, 19, 19, 10, 39, 46, 24],
       [49, 42, 48, 16, 42, 38, 17, 39, 49, 40],
       [24, 30, 20, 41, 43, 39, 10, 28, 33, 44]])

In [117]:
np.random.randint(1,100,(12,12))

array([[85, 79, 25, 10, 54,  4, 71, 25, 20,  1, 65, 57],
       [82, 80, 41, 64, 29, 39, 49, 55, 49, 20,  1, 69],
       [45,  7, 43, 79, 88, 83, 39, 92, 73, 45, 66, 30],
       [26, 11, 45, 92, 10, 62, 15, 30, 66, 96, 24, 21],
       [38, 87, 73, 32, 30, 96, 90,  5, 32, 47, 59, 37],
       [94, 32, 46, 47, 39, 54, 58, 84, 38, 58, 51, 49],
       [89, 85, 71, 88, 22, 28, 72, 27, 76, 77, 78, 17],
       [38, 26, 22, 29, 27, 99, 84, 59, 82, 16, 53, 80],
       [18, 64, 56,  6, 77, 60, 45,  8, 37, 38, 80, 63],
       [19, 53, 16, 78, 92, 30, 77, 88, 10, 23, 99, 83],
       [50, 87, 36, 85, 55, 89, 88, 95, 97, 76, 13, 40],
       [67, 77, 27, 96,  1, 46, 38, 62, 45, 95, 47, 98]])

# reshape

In [126]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [129]:
np.arange(1,15).reshape(14, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [130]:
b = np.random.randint(10,20,(5,4))
b

array([[10, 18, 16, 11],
       [18, 19, 15, 17],
       [11, 18, 12, 18],
       [12, 16, 10, 15],
       [11, 13, 15, 11]])

In [131]:
type(b)

numpy.ndarray

In [133]:
b

array([[10, 18, 16, 11],
       [18, 19, 15, 17],
       [11, 18, 12, 18],
       [12, 16, 10, 15],
       [11, 13, 15, 11]])

In [134]:
b[:]

array([[10, 18, 16, 11],
       [18, 19, 15, 17],
       [11, 18, 12, 18],
       [12, 16, 10, 15],
       [11, 13, 15, 11]])

In [137]:
b[2:4]

array([[11, 18, 12, 18],
       [12, 16, 10, 15]])

In [141]:
b

array([[10, 18, 16, 11],
       [18, 19, 15, 17],
       [11, 18, 12, 18],
       [12, 16, 10, 15],
       [11, 13, 15, 11]])

In [145]:
b[3,2]

10

In [146]:
b

array([[10, 18, 16, 11],
       [18, 19, 15, 17],
       [11, 18, 12, 18],
       [12, 16, 10, 15],
       [11, 13, 15, 11]])

In [147]:
b[1,-1]

17

In [148]:
b

array([[10, 18, 16, 11],
       [18, 19, 15, 17],
       [11, 18, 12, 18],
       [12, 16, 10, 15],
       [11, 13, 15, 11]])

In [149]:
b[2:3]

array([[11, 18, 12, 18]])

In [152]:
b[2:3]

array([[11, 18, 12, 18]])

In [153]:
b

array([[10, 18, 16, 11],
       [18, 19, 15, 17],
       [11, 18, 12, 18],
       [12, 16, 10, 15],
       [11, 13, 15, 11]])

In [157]:
b[0:-2]

array([[10, 18, 16, 11],
       [18, 19, 15, 17],
       [11, 18, 12, 18]])

In [158]:
b[:]

array([[10, 18, 16, 11],
       [18, 19, 15, 17],
       [11, 18, 12, 18],
       [12, 16, 10, 15],
       [11, 13, 15, 11]])

# python program to generat otp 

In [184]:
import random

def generate_otp(length=5):
    """Generate a numeric OTP of a specified length."""
    digits = '056789'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 5  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 88060


# 1. Array Creation Functions

In [22]:
import numpy as np

In [23]:
# create array
a = np.array([1,2,3,4])
print("array a :",a)

array a : [1 2 3 4]


In [24]:
# create an array with space evenly 
b = np.arange(0,10,2)
print(b)

[0 2 4 6 8]


In [25]:
# create array with linearly space value
c = np.linspace(0,1,5)
print("array c:", c)

array c: [0.   0.25 0.5  0.75 1.  ]


In [26]:
# create an array filled with zeros
d = np.zeros((2,2))
print("array d:\n",d)

array d:
 [[0. 0.]
 [0. 0.]]


In [27]:
# create an array filled with ones
e = np.ones((3,3))
print("array e : \n",e)

array e : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# create an identity matrix
f = np.eye(4)
print("identity matrix f: \n", f)

identity matrix f: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2 Array manipulation function

In [29]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("Reshape array a1:", reshaped)

Reshape array a1: [[1 2 3]]


In [30]:
# Flatten an array
f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1)
print("Flatten array :",flattened)

Flatten array : [1 2 3 4]


In [31]:
# Transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print('transposed array :\n', transposed)

transposed array :
 [[1 3]
 [2 4]]


In [32]:
# Stack arrays vertically
a2 = ([1,2])
b2 = ([3,4])
stacked = np.vstack([a2,b2])
print("Stacked array : \n",stacked)

Stacked array : 
 [[1 2]
 [3 4]]


# 3 Mathematical Functions

In [33]:
# Add two arrays
g = np.array([1,2,3,4])
added = np.add(g,2)
print("Added array:", added)

Added array: [3 4 5 6]


In [34]:
# Square each element
squared = np.power(g,2)
print("Square element:",squared)

Square element: [ 1  4  9 16]


In [35]:
# Square root of each element
sqrt_val = np.sqrt(g)
print("Square root :",sqrt_val)

Square root : [1.         1.41421356 1.73205081 2.        ]


In [36]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [41]:
print(a)
print(a1)

[1 2 3 4]
[1 2 3]


# 4 Stastical functions

In [55]:
# Mean
s = np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [56]:
# Standard deviation of an array
std_dev = np.std(s)
print('Standard deviation of s:',std_dev)

Standard deviation of s: 1.118033988749895


In [57]:
# Minimum element of an array
minimum = np.min(s)
print("Minimum of s:",minimum)

Minimum of s: 1


In [58]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:",maximum)

Max of s: 4


# 5 Linear Algebra Function

In [62]:
# create matrix of array
matrix = np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

In [63]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:",determinant)

Determinant of matrix: -2.0000000000000004


In [64]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Invers matrix : \n",inverse)

Invers matrix : 
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 6 Random Sampling Function

In [69]:
# Generate random values between 0 and 1
random_val = np.random.rand(3)
print("random val 0 & 1:",random_val)

random val 0 & 1: [0.48216601 0.04848789 0.61831633]


In [74]:
# Generate random integers
random_ints = np.random.randint(0,10, size=5)
print("random integer :",random_ints)

random integer : [5 1 4 3 6]


# 7 Boolean & Logical Functions

In [78]:
# Check if all elements are True / False    any value change different output
# all
logical_test = np.array([True,False,True])
all_test = np.all(logical_test)
print("All element True:",all_test)

All element True: False


In [79]:
# Check if any elements are True
# any
any_test = np.any(logical_test)
print("any element check:",any_test)

any element check: True


# 8 Set Operations

In [80]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [81]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# 9 Array Attribute Functions

In [82]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int32


# 10 Other Functions

In [83]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [84]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 12


In [85]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
